# Generated by Django 4.2.5 on 2023-10-10 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='status',
            name='dataHoraCriacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
