# Generated by Django 4.2.5 on 2023-10-10 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_emprestimo_datadevolucao_emprestimo_dataemprestimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='dataHoraCriacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
